package com.euler.problem;

/**
 * @author Hasan
 * @version java version "1.8.0_92" Each new term in the Fibonacci sequence is
 * generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering
 * the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * IF you write it on interview you are failed! Follow Dynamic Programming
 * Don't run this :D
 */
public class Problem_2_1 {

     public static void main(String[] args) {
          int m;
          int total = 0;
          for (int i = 0; i < 4_000_000; i++) {
               m = fibonacci(i);
               System.out.println(m);
               if (m % 2 == 0) {
                    total = total + m;
                    
               }
               if(total>=4_000_000) break;
          }
          System.out.println("Total = " + total);
     }

     private static int fibonacci(int i) {
          if (i == 0) {
               return 1;
          }
          if (i == 1) {
               return 1;
          } else {
               return fibonacci(i - 1) + fibonacci(i - 2);
          }
     }
}
